# Generated by Django 5.2 on 2025-05-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('completed', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
